"""Research-only stop-distance x time-horizon matrix.

The production signal engine is frozen. This experiment replays the exact
historical signals generated by the existing research adapter, then changes
only the synthetic stop distance and observation horizon. It also records
MAE/MFE so stop candidates can be judged by path behaviour, not win rate alone.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean, median

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from historical_data import load_six_months
from market_regime import classify as classify_regime
from research_config import HISTORICAL_DAYS
from signal_engine import ContestoMercato
from signal_engine_replay_adapter_fast import analyze_context_at

SYMBOL = "BTCUSDT"
TP_PCT = 0.05
STOP_PCTS = (0.005, 0.01, 0.02, 0.05)
HORIZONS = (25, 50, 100, 200, 500)
OUT = ROOT / "research" / "stop_distance_time_horizon_results.json"


def _levels(direction: str, entry: float, stop_pct: float) -> tuple[float, float]:
    if direction == "LONG":
        return entry * (1 - stop_pct), entry * (1 + TP_PCT)
    return entry * (1 + stop_pct), entry * (1 - TP_PCT)


def evaluate_path(direction: str, entry: float, future: list[dict], stop_pct: float, horizon: int) -> dict:
    stop, tp = _levels(direction, entry, stop_pct)
    window = future[:horizon]
    mae_values: list[float] = []
    mfe_values: list[float] = []
    outcome = "OPEN"
    exit_bar = None

    for bars, candle in enumerate(window, start=1):
        high = float(candle["high"])
        low = float(candle["low"])
        if direction == "LONG":
            adverse = low / entry - 1.0
            favorable = high / entry - 1.0
            hit_sl = low <= stop
            hit_tp = high >= tp
        else:
            adverse = 1.0 - high / entry
            favorable = 1.0 - low / entry
            hit_sl = high >= stop
            hit_tp = low <= tp
        mae_values.append(adverse)
        mfe_values.append(favorable)
        if hit_sl or hit_tp:
            exit_bar = bars
            # Same-candle TP+SL is resolved conservatively as SL, matching
            # historical_replay.evaluate_forward_result().
            outcome = "SL" if hit_sl else "TP"
            break

    # Path MAE/MFE over the complete observation window are useful even when
    # the synthetic trade closes early; report both the closed-path values and
    # the full-horizon excursion separately below.
    full_mae: list[float] = []
    full_mfe: list[float] = []
    for candle in window:
        high = float(candle["high"])
        low = float(candle["low"])
        if direction == "LONG":
            full_mae.append(low / entry - 1.0)
            full_mfe.append(high / entry - 1.0)
        else:
            full_mae.append(1.0 - high / entry)
            full_mfe.append(1.0 - low / entry)

    return {
        "outcome": outcome,
        "exit_bar": exit_bar,
        "mae_pct": min(full_mae, default=0.0) * 100.0,
        "mfe_pct": max(full_mfe, default=0.0) * 100.0,
        "path_mae_until_exit_pct": min(mae_values, default=0.0) * 100.0,
        "path_mfe_until_exit_pct": max(mfe_values, default=0.0) * 100.0,
    }


def summarize(rows: list[dict]) -> dict:
    n = len(rows)
    closed = [r for r in rows if r["outcome"] != "OPEN"]
    tp = sum(r["outcome"] == "TP" for r in rows)
    sl = sum(r["outcome"] == "SL" for r in rows)
    return {
        "signals": n,
        "tp": tp,
        "sl": sl,
        "open": n - tp - sl,
        "win_rate_closed_pct": round(100 * tp / len(closed), 4) if closed else None,
        "mae_mean_pct": round(mean(r["mae_pct"] for r in rows), 4) if rows else None,
        "mae_median_pct": round(median(r["mae_pct"] for r in rows), 4) if rows else None,
        "mfe_mean_pct": round(mean(r["mfe_pct"] for r in rows), 4) if rows else None,
        "mfe_median_pct": round(median(r["mfe_pct"] for r in rows), 4) if rows else None,
    }


def generate_signals(candles: list[dict], timeframe: str) -> list[dict]:
    ctx = ContestoMercato(candles)
    signals: list[dict] = []
    next_free_index = 60
    for i in range(60, len(candles) - 1):
        if i < next_free_index:
            continue
        analysis = analyze_context_at(ctx, i)
        if not analysis or analysis.get("classificazione", {}).get("livello") != "FORTE":
            continue
        plan = analysis.get("trade_plan")
        if not plan:
            continue
        direction = plan.get("direction")
        entry = float(plan.get("entry", 0) or 0)
        if direction not in {"LONG", "SHORT"} or entry <= 0:
            continue
        baseline_stop = float(plan.get("stop_loss", 0) or 0)
        signals.append({
            "candle_index": i,
            "timestamp": candles[i].get("timestamp"),
            "timeframe": timeframe,
            "direction": direction,
            "regime": classify_regime(candles[: i + 1]),
            "entry": entry,
            "baseline_stop": baseline_stop,
            "future": candles[i + 1:i + 501],
        })
        # Preserve the existing replay's non-overlapping signal convention.
        # The baseline plan determines when the next independent trade may start.
        baseline_result = evaluate_path(direction, entry, candles[i + 1:i + 501],
                                        abs(baseline_stop / entry - 1.0), 500)
        next_free_index = i + max(1, int(baseline_result.get("exit_bar") or 1)) + 1
    return signals


def run() -> dict:
    end = datetime.now(timezone.utc)
    datasets = load_six_months(SYMBOL, end)
    result = {
        "generated_at": end.isoformat(),
        "symbol": SYMBOL,
        "history_days": HISTORICAL_DAYS,
        "tp_pct": TP_PCT * 100,
        "stop_distances_pct": [x * 100 for x in STOP_PCTS],
        "horizons_bars": list(HORIZONS),
        "timeframes": {},
    }

    for timeframe, candles in datasets.items():
        signals = generate_signals(candles, timeframe)
        matrix = []
        for stop_pct in STOP_PCTS:
            for horizon in HORIZONS:
                rows = []
                for signal in signals:
                    metrics = evaluate_path(signal["direction"], signal["entry"], signal["future"], stop_pct, horizon)
                    rows.append({**signal, **metrics})
                matrix.append({
                    "stop_pct": stop_pct * 100,
                    "horizon_bars": horizon,
                    "summary": summarize(rows),
                    "by_direction": {
                        d: summarize([r for r in rows if r["direction"] == d])
                        for d in ("LONG", "SHORT")
                    },
                    "by_regime": {
                        regime: summarize([r for r in rows if r["regime"] == regime])
                        for regime in sorted({r["regime"] for r in rows})
                    },
                })
        result["timeframes"][timeframe] = {
            "signals": len(signals),
            "matrix": matrix,
        }
        print(f"MATRIX {timeframe}: {len(signals)} signals")
    return result


if __name__ == "__main__":
    OUT.write_text(json.dumps(run(), indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"WROTE {OUT}")
